[project]
name = "mosamaticinsights"
version = "1.0.2"
description = ""
readme = "README.md"
requires-python = ">=3.11,<3.12"
authors = [{ name = "Brecheisen", email = "r.brecheisen@maastrichtuniversity.nl" }]

dependencies = [
    "pyside6>=6.6",
    "pydicom>=3.0.1",
    "numpy>=1.26.4",
    "pandas>=2.3.2",
    "pillow>=11.3.0",
    "python-gdcm>=3.0.26",
    "rbeesoft>=2.0.20",
    "torch==2.5.1",
    "torchvision>=0.20.1",
    "torchsummary",
    "tensorflow==2.15.*; platform_system == 'Linux'",
    "tensorflow-intel==2.15.0; platform_system == 'Windows'",
    "tensorflow-macos==2.15.0; platform_system == 'Darwin' and platform_machine == 'arm64'",
    "tensorboard==2.15.2",
    "tensorboard-data-server==0.7.2",
    "tensorflow-io-gcs-filesystem==0.31.0; platform_system == 'Windows'",
    "tensorflow-io-gcs-filesystem>=0.31.0; platform_system == 'Darwin' and platform_machine == 'arm64'",
    "totalsegmentator>=2.11.0",
    "pendulum>=3.1.0",
    "simpleitk>=2.5.2", 
    "matplotlib",
]

[project.scripts]
mosamaticinsights = "mosamaticinsights.main:main"

[project.optional-dependencies]
dev = [
  "pytest>=8.4.1",
  "pyinstaller>=6.17.0",
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }
# this is the setuptools replacement for your "models.py" include:
py-modules = ["models"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.bumpversion]
current_version = "1.0.2"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = '(?m)^version\\s*=\\s*"{current_version}"\\s*$'
replace = 'version = "{new_version}"'